### ISSUE TITLE
Roll Call

### ISSUE THREAD

**Issue by choochootrain** [MissionBit/spring-2015-intermediate-web-python#1]
Get a sheet of paper and a sharpie
Write your name on the sheet
Use photobooth to take a picture of yourself
Drag and drop it in a comment here
:cookie:

**Comment by califoxco** [comment]
![photo on 2-2-15 at 4 59 pm](https://cloud.githubusercontent.com/assets/10820715/6012432/f394e400-aafc-11e4-86e4-2669685e309a.jpg)

**Comment by turntSNACO** [comment]
![photo on 2-2-15 at 5 10 pm](https://cloud.githubusercontent.com/assets/8785298/6012452/1a68ddc0-aafd-11e4-93da-8c903d57ca33.jpg)

**Comment by cjlim2007** [comment]
![photo on 2-2-15 at 5 00 pm](https://cloud.githubusercontent.com/assets/6590552/6012446/1166393e-aafd-11e4-9d26-9cdb606227e8.jpg)

**Comment by mkahney** [comment]
![photo on 2-2-15 at 5 00 pm](https://cloud.githubusercontent.com/assets/6610877/6012450/15b8103e-aafd-11e4-9b8c-ffdee6401f5d.jpg)

**Comment by eliaslfox** [comment]
![images](https://cloud.githubusercontent.com/assets/6886632/6012813/824b1404-ab01-11e4-8e0a-e9d6b44ea7af.jpg)

Every time you write crappy code..
...God kills a kitten :skull: .

Knock, knock.
Who’s there?
vi.
vi who?
vi aren’t you using emacs!?

**Comment by ckahookele** [comment]
![photo on 2-2-15 at 5 06 pm](https://cloud.githubusercontent.com/assets/8785857/6012530/fd2c3f80-aafd-11e4-895f-47fc47fc1726.jpg)

**Comment by GiselaK** [comment]
![photo on 2-2-15 at 5 04 pm](https://cloud.githubusercontent.com/assets/6656170/6012548/3c8e4e0c-aafe-11e4-9643-b0d6ef9f5b2f.jpg)

**Comment by ryko9** [comment]
![photo on 2-2-15 at 5 11 pm](https://cloud.githubusercontent.com/assets/10820731/6012642/1394b03a-aaff-11e4-810d-34652218ace3.jpg)

**Comment by ckahookele** [comment]
![photo on 2-2-15 at 5 15 pm 3](https://cloud.githubusercontent.com/assets/8785857/6012664/69d84c86-aaff-11e4-96cd-9b638ed6510f.jpg)

**Comment by MostExcellent** [comment]
![photo on 2-2-15 at 5 18 pm](https://cloud.githubusercontent.com/assets/6345435/6012723/556ee2c2-ab00-11e4-975c-b403013508b9.jpg)

**Comment by findjustin** [comment]
![photo on 2-2-15 at 5 27 pm](https://cloud.githubusercontent.com/assets/7944949/6012839/c53307b8-ab01-11e4-940e-b139b289e2d2.jpg)

**Comment by choochootrain** [comment]
:+1:

**Comment by thwinston** [comment]
![theophoto](https://cloud.githubusercontent.com/assets/6656095/6053077/d11718d2-ac8f-11e4-90e2-f923ea8297b2.jpg)

**Comment by olinkahney** [comment]
![photo on 2-4-15 at 5 04 pm](https://cloud.githubusercontent.com/assets/8786125/6053284/565943b0-ac92-11e4-84c7-6f8f0c32ad75.jpg)
