### ISSUE TITLE
Group Brainstorm

### ISSUE THREAD

**Issue by choochootrain** [MissionBit/spring-2015-intermediate-web-python#7]
List your group's ideas for each round here. After we're done, you'll have a giant list of ideas to build or inspire you! :hamburger: 

Some questions you should try to answer for each idea:
- What does it do?
- How does it solve a problem or make a task easier or more fun?
- Who would use it?
- How do you use it?

**Comment by choochootrain** [comment]
Theme: School

**Comment by eliaslfox** [comment]
# Topics

## School
- Tracking HW :paperclip: 
- Teacher Rating/Class Rating :+1: 
- Thunder Dome :zap: 
- Geometric Mathproblem solvers :pencil2:

**Comment by ryko9** [comment]
test answer sharing system
homework sharing system
grade changing system
teacher changing system
take control of teachers computer system
food ordering system
question sharing system
homework help system
homework answers system
bathroom cleaning list
available toilet stalls tracker
rate your toilet
toilet wait list system

**Comment by ckahookele** [comment]
School Related
-Arena(self scheduling)
-Homework tracking 
-Teacher rating
-Anonymous questions to teachers
-Class study groups
-News texting/facebook
-College requirement tracking
-Planner app

**Comment by choochootrain** [comment]
doodling on your notes to help people learn and keep you focused
drown out distracting noises during tests
reminders for what you need to study for on a test
turn substitute teacher into a game - get points for learning instead of distracting people
upload art and have other people upvote it and stuff

**Comment by choochootrain** [comment]
Theme: Aliens

**Comment by cjlim2007** [comment]
brainstorm session 1: school

remake arena cuz its a piece of crap
tutoring site
wolfram alpha type thing
time management for students
a website with pdfs of all textbooks
multiple problems solver

**Comment by choochootrain** [comment]
Theme: Aliens

**Comment by MostExcellent** [comment]
ayy lmao :alien:

**Comment by ryko9** [comment]
platform game
hardware rating system(alienware)
UFO game
Alien Face Generator
UFO Generator (add UFOs onto pictures)

**Comment by ryko9** [comment]
alienmingle.com
alienyoutube.com
alienchannel
alienware
ayyy lmao virus 
alien breeding simulator
alien abduction simulator
alien kfc simulator
alien petstore
probe simulator 2015
human eating alien simulator
alien goat simulator
predator vs alien
alien vs predator

**Comment by GiselaK** [comment]
Track Alien Siting (Geo & TimeStamp)
Crop Circles
Alien Suspects
Conspiracy Theories
Shelters Incase Alien Attack
Translates Text to Pictures
Brag About Beating Up Aliens

**Comment by olinkahney** [comment]
Theme: Aliens
Obama yo Mama is an alien reptile illuminati space wizard from uranus
Heavens Gate: kill as many people as possible with religion about aliens
E.T. is an alien that is a cool alien that kills peoplee . . . . . . . . . . . 
frogger with illegal aliens

**Comment by cjlim2007** [comment]
brainstorm  session 2: aliens

how survive alien apocalypse app
planet exploration app
illuminati app
triangle detector app for the illuminatissss
life detector to detect life on other planets
cleverbot with alien skin
planet generator app
planet/star naming app. because if you find something nasa hasn’t already found you go name it yourself 
a very legit and accurate constellation map

**Comment by choochootrain** [comment]
- havewefoundaliensyet.com - like http://www.hasthelhcdestroyedtheearth.com/ but for aliens

**Comment by GiselaK** [comment]
- Yelp for technically challenged
- One random health fact
- Non-biased UrbanSpoon
- Brings diff. food auto everyday
- Order food program finds place that serves
- Restaurant Very Negative (pics of bad things you have seen)
- Selfies with waiters
- Discounts of Restaurants in area
- How Disappointing McDonalds is
- Cover Ads with food
- Two diff. restaurants. Rate them in comparison
- Post awesome food fight videos
- Catseatingfood.com

**Comment by ckahookele** [comment]
Food
-random food generator
-food suggestions based on personal ratings of other restaurants (goodreads for food)
-anti spam subscription

**Comment by ryko9** [comment]
japanese food simulator 2015
i am hot dog - the movie
chinesfoodmingle.com
food dictionary
google translate food
foodstagram
foodcebook
foodwitter
food of legends
counter strike: food
defense of the foods
watch food 24 hours
watch food dry.com
twitch.com/food
reddit.com/r/food
food getting cooked simulator
harvest animals for food simulator
fastfoodmingle.com
chickentender
chickenmingle.com

**Comment by GiselaK** [comment]
Saltontheinternet

**Comment by MostExcellent** [comment]
recipe wiki
free food (somehow)
soft-serve vending machine
blackmail spam
meal/grocery list planner

**Comment by choochootrain** [comment]
Theme: Sites to visit every day

**Comment by ryko9** [comment]
whattimeisit.com
iswhattimeisitcomworking.com
whatdayisit.com
howmanydaysleftofschool.com
doyouhavecancer.com
doihavestd.com
dailymingle.com
isittimetoeatyet.com
isthereschooltoday.com
checkhomework.com
checkmyemailforme.com
isittimeyet.com
winteriscoming.com

**Comment by califoxco** [comment]
1. Thrid world google
2. Blackmail.com
3. Gangsterchateroom.com(gangsters in one gang visit the website to communicate)
4. physics solver website
5. watchdogs.com
6. server up? (tell you if some servers are up)
7. cats or dogs? (tells you if someone is a cat or a dog person by going over all this person's web-presence like facebook instagram)

**Comment by ckahookele** [comment]
Website You Would Check Daily
-Internships/Career Opportunities
-Automatically Github Commits
-Grade Changer
-Homework tracker/Planner
-Class Timing Schedule
-Online Attendance Marker
-Personalized News Page
-Random Happiness
-Video chatting 
-Fortune generator

**Comment by cjlim2007** [comment]
pony pics
hot dog pics
a clock. no really its just a straight up clock. it tells time. what did you expect?
a website that shows random stupid things
social media website posting pictures of cats and other various animals in subsections
forum for homework help

**Comment by choochootrain** [comment]
select categories of news to be sent emails daily
filter out boring pictures on instagram
calls you when it rains
reddit
free food (college)

**Comment by choochootrain** [comment]
Social Network Ideas

**Comment by choochootrain** [comment]
facebook but only dislikes
twitter
must type over 140 characters
ever post gets deleted every week
name board that can support uploading different files
hashtags and mentions don't count towards your 140 character limit
all comments are photos
limit the length of videos - vine
all media is free

**Comment by choochootrain** [comment]
Coding ideas

**Comment by choochootrain** [comment]
free web hosting through watching ads - every 20 seconds you get shown a catpcha to make sure you watch
get alerts on your phone
lock screen for your phone is a captcha
give a website to pull data and display it in a theme
online mentor to get live help on projects
official error message database
user authentication api so you don't have to write it
website that connects companies that need engineers with coders who want to work part time - mechanical turk for coding
batch rename a bunch of files
change muni lines so someone controls trains online - get paid to drive public transit
everyone on the train can vote on when to stop - collaborative stops
clipper card on your phone
track down your wallet with gps
self destructing wallet
find my iphone
remote access for phones - use someone else's phone from your phone
car talks back when you try to open it
network where other people can do your laundry if they are walking by your house

**Comment by choochootrain** [comment]
wizardry

**Comment by choochootrain** [comment]
use a webcam to remotely fire nerfs at people
a tank that launches nerf guns
a quadcopter that drops water balloons
a small mobile nerf turret
fire monopoly money at people
paper airplane turret - it also folds the paper airplane and keeps track of the wind direction
a robot that shoots fireballs and napalm
prank people with a bootable windows disk that tricks them into thinking their files are gone
connect 2 people with a phone call
bump phones to give battery life
a chat network for people on the same muni bus as you
shazam for videos or objects
website where you can only comment with movie quotes
automated food preparer
